#define LIGHTPINK               0xffb6c1
#define PINK                    0xffc0cb
#define CRIMSON                 0xdc143c
#define LAVENDERBLUSH           0xfff0f5
#define PALEVIOLETRED           0xdb7093
#define HOTPINK                 0xff69b4
#define DEEPPINK                0xff1493
#define MEDIUMVIOLETRED         0xc71585
#define ORCHID                  0xda70d6
#define THISTLE                 0xd8bfd8
#define PLUM                    0xdda0dd
#define VIOLET                  0xee82ee
#define MAGENTA                 0xff00ff
#define FUCHSIA                 0xff00ff
#define DARKMAGENTA             0x8b008b
#define PURPLE                  0x800080
#define MEDIUMORCHID            0xba55d3
#define DARKVIOLET              0x9400d3
#define DARKORCHID              0x9932cc
#define INDIGO                  0x4b0082
#define BLUEVIOLET              0x8a2be2
#define MEDIUMPURPLE            0x9370db
#define MEDIUMSLATEBLUE         0x7b68ee
#define SLATEBLUE               0x6a5acd
#define DARKSLATEBLUE           0x483d8b
#define LAVENDER                0xe6e6fa
#define GHOSTWHITE              0xf8f8ff
#define BLUE                    0x0000ff
#define MEDIUMBLUE              0x0000cd
#define MIDNIGHTBLUE            0x191970
#define DARKBLUE                0x00008b
#define NAVY                    0x000080
#define ROYALBLUE               0x4169e1
#define CORNFLOWERBLUE          0x6495ed
#define LIGHTSTEELBLUE          0xb0c4de
#define LIGHTSLATEGRAY          0x778899
#define SLATEGRAY               0x708090
#define DODGERBLUE              0x1e90ff
#define ALICEBLUE               0xf0f8ff
#define STEELBLUE               0x4682b4
#define LIGHTSKYBLUE            0x87cefa
#define SKYBLUE                 0x87ceeb
#define DEEPSKYBLUE             0x00bfff
#define LIGHTBLUE               0xadd8e6
#define POWDERBLUE              0xb0e0e6
#define CADETBLUE               0x5f9ea0
#define AZURE                   0xf0ffff
#define LIGHTCYAN               0xe0ffff
#define PALETURQUOISE           0xafeeee
#define CYAN                    0x00ffff
#define AQUA                    0x00ffff
#define DARKTURQUOISE           0x00ced1
#define DARKSLATEGRAY           0x2f4f4f
#define DARKCYAN                0x008b8b
#define TEAL                    0x008080
#define MEDIUMTURQUOISE         0x48d1cc
#define LIGHTSEAGREEN           0x20b2aa
#define TURQUOISE               0x40e0d0
#define AQUAMARINE              0x7fffd4
#define MEDIUMAQUAMARINE        0x66cdaa
#define MEDIUMSPRINGGREEN       0x00fa9a
#define MINTCREAM               0xf5fffa
#define SPRINGGREEN             0x00ff7f
#define MEDIUMSEAGREEN          0x3cb371
#define SEAGREEN                0x2e8b57
#define HONEYDEW                0xf0fff0
#define LIGHTGREEN              0x90ee90
#define PALEGREEN               0x98fb98
#define DARKSEAGREEN            0x8fbc8f
#define LIMEGREEN               0x32cd32
#define LIME                    0x00ff00
#define FORESTGREEN             0x228b22
#define GREEN                   0x008000
#define DARKGREEN               0x006400
#define CHARTREUSE              0x7fff00
#define LAWNGREEN               0x7cfc00
#define GREENYELLOW             0xadff2f
#define DARKOLIVEGREEN          0x556b2f
#define YELLOWGREEN             0x9acd32
#define OLIVEDRAB               0x6b8e23
#define BEIGE                   0xf5f5dc
#define LIGHTGOLDENRODYELLOW    0xfafad2
#define IVORY                   0xfffff0
#define LIGHTYELLOW             0xffffe0
#define YELLOW                  0xffff00
#define OLIVE                   0x808000
#define DARKKHAKI               0xbdb76b
#define LEMONCHIFFON            0xfffacd
#define PALEGOLDENROD           0xeee8aa
#define KHAKI                   0xf0e68c
#define GOLD                    0xffd700
#define CORNSILK                0xfff8dc
#define GOLDENROD               0xdaa520
#define DARKGOLDENROD           0xb8860b
#define FLORALWHITE             0xfffaf0
#define OLDLACE                 0xfdf5e6
#define WHEAT                   0xf5deb3
#define MOCCASIN                0xffe4b5
#define ORANGE                  0xffa500
#define PAPAYAWHIP              0xffefd5
#define BLANCHEDALMOND          0xffebcd
#define NAVAJOWHITE             0xffdead
#define ANTIQUEWHITE            0xfaebd7
#define TAN                     0xd2b48c
#define BURLYWOOD               0xdeb887
#define BISQUE                  0xffe4c4
#define DARKORANGE              0xff8c00
#define LINEN                   0xfaf0e6
#define PERU                    0xcd853f
#define PEACHPUFF               0xffdab9
#define SANDYBROWN              0xf4a460
#define CHOCOLATE               0xd2691e
#define SADDLEBROWN             0x8b4513
#define SEASHELL                0xfff5ee
#define SIENNA                  0xa0522d
#define LIGHTSALMON             0xffa07a
#define CORAL                   0xff7f50
#define ORANGERED               0xff4500
#define DARKSALMON              0xe9967a
#define TOMATO                  0xff6347
#define MISTYROSE               0xffe4e1
#define SALMON                  0xfa8072
#define SNOW                    0xfffafa
#define LIGHTCORAL              0xf08080
#define ROSYBROWN               0xbc8f8f
#define INDIANRED               0xcd5c5c
#define RED                     0xff0000
#define BROWN                   0xa52a2a
#define FIREBRICK               0xb22222
#define DARKRED                 0x8b0000
#define MAROON                  0x800000
#define WHITE                   0xffffff
#define WHITESMOKE              0xf5f5f5
#define GAINSBORO               0xdcdcdc
#define LIGHTGREY               0xd3d3d3
#define SILVER                  0xc0c0c0
#define DARKGRAY                0xa9a9a9
#define GRAY                    0x808080
#define DIMGRAY                 0x696969
#define BLACK                   0x000000

